// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Provide safe fallbacks so the app can still render when environment variables
// are missing (e.g., local preview builds). Using placeholder credentials
// prevents the Supabase client from throwing at initialization time which
// previously resulted in a blank screen.
const supabaseUrl = SUPABASE_URL || "https://placeholder.supabase.co";
const supabaseKey = SUPABASE_PUBLISHABLE_KEY || "public-anon-key";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Using placeholder credentials; data features will be limited."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});